// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'arxiv2zh-menu-account'
  | 'arxiv2zh-menu-clear-session'
  | 'arxiv2zh-menu-input'
  | 'arxiv2zh-menu-redownload'
  | 'arxiv2zh-menu-root'
  | 'arxiv2zh-menu-tasks'
  | 'arxiv2zh-menu-translate'
  | 'arxiv2zh-menu-view-site'
  | 'arxiv2zh-pref-account-heading'
  | 'arxiv2zh-pref-account-note'
  | 'arxiv2zh-pref-behavior-heading'
  | 'arxiv2zh-pref-clear-session'
  | 'arxiv2zh-pref-history-retention'
  | 'arxiv2zh-pref-open-account'
  | 'arxiv2zh-pref-open-after-single'
  | 'arxiv2zh-pref-poll-interval'
  | 'arxiv2zh-pref-service-heading'
  | 'arxiv2zh-pref-service-note'
  | 'arxiv2zh-pref-service-url'
  | 'arxiv2zh-prefs-title';
