// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "serviceURL": string;
      "openAfterSingle": boolean;
      "pollInterval": number;
      "historyRetentionDays": number;
    };
  }
}
